// File generated by hand from the google-services.json / GoogleService-Info.plist
// provided for the manor-ba6ec Firebase project. Regenerate with `flutterfire configure`
// if the Firebase project or registered apps ever change.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'this app only registers Android and iOS apps in Firebase.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5_I2mxvCdU2oCMQODsX7QxQs4UWMkxIE',
    appId: '1:364568536342:android:ff84a3ec14c7756d655c37',
    messagingSenderId: '364568536342',
    projectId: 'manor-ba6ec',
    storageBucket: 'manor-ba6ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYx1yiFT4bzsm7jkHFrAq3cHoagT3Nhc',
    appId: '1:364568536342:ios:6e4a8dd7bfe80689655c37',
    messagingSenderId: '364568536342',
    projectId: 'manor-ba6ec',
    storageBucket: 'manor-ba6ec.firebasestorage.app',
    iosBundleId: 'co.manorestates.manor',
  );
}
